version: "3"
services:
  backend:
    # image: 51616253c30b
    build:
      context: .
    volumes_from:
      - sync
    networks:
      - "common"
  frontend:
    image: nginx:latest
    volumes:
      - ./nginx/conf.d:/etc/nginx/conf.d
      - ./nginx/html:/usr/share/nginx/html
    restart: always
    ports: ["80:80"]
    depends_on: ["backend"]
    networks:
      - "common"
networks:
  common:
    driver: bridge
volumes:
  grav_sync:
    driver_opts:
      type: none
      device: grav/user
      o: bind