FROM docker.pkg.github.com/y-kimura-opst/grav-lab/base:main
RUN rm -fR /var/www/grav/user
COPY --chown=grav:www-data grav/user /var/www/grav/user
WORKDIR /var/www/grav
COPY --chown=grav:www-data dev_run.sh /var/www/grav/bin/dev_run.sh
RUN chmod +x /var/www/grav/bin/* \
 && bin/gpm install -y admin
CMD [ "/var/www/grav/bin/dev_run.sh" ]
