apiVersion: v1
kind: PersistentVolume
metadata:
  name: grav-sync
spec:
  capacity: 
    storage: 5Gi
  volumeMode: Filesystem
  accessModes:
  - ReadWriteMany
  persistentVolumeReclaimPolicy: Delete
  hostPath:
    path: /tmp/hostpath_pv/grav
