apiVersion: v1
kind: Secret
metadata:
  name: github-registry
  namespace: grav
type: kubernetes.io/dockerconfigjson

data:
  .dockerconfigjson: eyJhdXRocyI6eyJkb2NrZXIucGtnLmdpdGh1Yi5jb20iOnsidXNlcm5hbWUiOiJ5LWtpbXVyYS1vcHN0IiwicGFzc3dvcmQiOiI5M2Q0OTZmMGE1OTBmNDNlZjYxYTQ4MDZkNTQyNGIxMzE5ZDFmMjI1IiwiZW1haWwiOiJraW11cmEueUBvcHN0LmNvLmpwIiwiYXV0aCI6ImVTMXJhVzExY21FdGIzQnpkRG81TTJRME9UWm1NR0UxT1RCbU5ETmxaall4WVRRNE1EWmtOVFF5TkdJeE16RTVaREZtTWpJMSJ9fX0=
