apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: grav-sync
  namespace: grav
spec:
  accessModes:
    - ReadWriteMany
  volumeMode: Filesystem
  volumeName: grav-sync
  storageClassName: "change to production storageclass"
  resources:
    requests:
      storage: 1Gi
    limits:
      storage: 2Gi
