apiVersion: v1
kind: Secret
metadata:
  name: github-registry
  namespace: grav
type: kubernetes.io/dockerconfigjson
stringData:
  .dockerconfigjson: '{"auths":{"docker.pkg.github.com":{"username":"<change-to-githubuser>","password":"<change-to-github-personalaccesstoken","email":"aaa@example.com"}}}'
