name: Docker Base Image CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
  schedule:
    - cron:  '0 12 * * *'
  workflow_dispatch:

env:
  GITHUB_PKG_REPO: "docker.pkg.github.com"
  IMAGE_NAME: "${{ github.repository }}"
  DOCKER_BUILDKIT: "1"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Set Environment
        run: |
          if [ "$GITHUB_HEAD_REF" != "" ]
          then
            echo "PR時はソースブランチ名がタグ名になります。"
            TAG_NAME=$GITHUB_HEAD_REF
          else
            echo "PR以外の時はベースブランチ名がタグ名になります。"
            TAG_NAME=${GITHUB_REF##*/}
          fi
          echo IMAGE_IDENTITY="${GITHUB_PKG_REPO}/${IMAGE_NAME}/grav:${TAG_NAME}" >> $GITHUB_ENV

      - name: Get Environment
        run: |
          env
    
      - name: Login GitHub Package
        run: |
          echo $GHP_TOKEN | docker login $GITHUB_PKG_REPO -u $GHP_USER --password-stdin
        env:
          GHP_USER: ${{ github.actor }}
          GHP_TOKEN: ${{ github.token }}

      - name: Hadolint the Dockerfile.base
        run: |
          docker run --rm -i \
            -v $PWD/.hadolint.yaml:/root/.config/hadolint.yaml \
            hadolint/hadolint < Dockerfile.base

      - name: Build the Docker image
        run: |
          docker build . -f Dockerfile.base --tag "${IMAGE_IDENTITY}"

      - name: Test the Docker image
        run: |
          docker run --name test -d -p 9000:8080 "${IMAGE_IDENTITY}"
          sleep 3
          curl -LsS --retry 10 \
            --retry-delay 3 \
              http://localhost:9000 \
            | grep "GravCMS" \
            || FAIL=true
          docker stop test
          docker rm test
          if [ "$FAIL" = "true" ]
          then
            echo "container did not start correctly... something wrong..."
            exit 1
          fi

      - name: Scan image
        run: |
          docker run --rm -v /var/run/docker.sock:/var/run/docker.sock \
            -v ${HOME}/.cache:/root/.cache aquasec/trivy:latest --exit-code 1 "${IMAGE_IDENTITY}"
      
      - name: Inspect image
        run: |
          docker inspect "${IMAGE_IDENTITY}"

      - name: Push Github Package
        run: |
          echo "docker push ${IMAGE_IDENTITY}"
          docker push "${IMAGE_IDENTITY}"
